default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: graduation_development

  

test:
  <<: *default
  database: graduation_test


production:
  <<: *default
  database: graduation_production
  username: graduation
  password: <%= ENV['GRADUATION_DATABASE_PASSWORD'] %>
